### ISSUE TITLE
algorithm.stock 包找不到，报红 应该如何处理

### ISSUE THREAD

**Issue by Yanbuc** [Stock-Fund/XCrawler#4]

**Comment by jeffreyrobeson** [comment]
Traceback (most recent call last):
  File "E:\software\XCrawler\main.py", line 10, in <module>
    import src
  File "E:\software\XCrawler\src\__init__.py", line 3, in <module>
    import src.html
  File "E:\software\XCrawler\src\html\__init__.py", line 11, in <module>
    from src.html.stockcustomcrawler import getStockData_datareader, showStockData
  File "E:\software\XCrawler\src\html\stockcustomcrawler.py", line 6, in <module>
    import src.quantifytest as quantifytest
  File "E:\software\XCrawler\src\quantifytest\__init__.py", line 1, in <module>
    from src.quantifytest.stock_quantify_test import (
  File "E:\software\XCrawler\src\quantifytest\stock_quantify_test.py", line 3, in <module>
    from algorithm.stock import Stock
ModuleNotFoundError: No module named 'algorithm.stock'; 'algorithm' is not a package

**Comment by akeboshi1** [comment]
> Traceback (most recent call last): File "E:\software\XCrawler\main.py", line 10, in import src File "E:\software\XCrawler\src__init__.py", line 3, in import src.html File "E:\software\XCrawler\src\html__init__.py", line 11, in from src.html.stockcustomcrawler import getStockData_datareader, showStockData File "E:\software\XCrawler\src\html\stockcustomcrawler.py", line 6, in import src.quantifytest as quantifytest File "E:\software\XCrawler\src\quantifytest__init__.py", line 1, in from src.quantifytest.stock_quantify_test import ( File "E:\software\XCrawler\src\quantifytest\stock_quantify_test.py", line 3, in from algorithm.stock import Stock ModuleNotFoundError: No module named 'algorithm.stock'; 'algorithm' is not a package

算法项目我没有发布release包，你可以https://github.com/Stock-Fund/algorithm在这个项目里，自己打包，然后在python环境下安装algorithm包

**Comment by akeboshi1** [comment]
> 算法项目我没有发布release包，你可以 https://github.com/Stock-Fund/algorithm
> 在这个项目里，自己打包，然后在python环境下安装algorithm包

算法项目我没有发布release包，你可以 https://github.com/Stock-Fund/algorithm
在这个项目里，自己打包，然后在python环境下安装algorithm包

**Comment by akeboshi1** [comment]
算法项目我没有发布release包，你可以 https://github.com/Stock-Fund/algorithm
在这个项目里，自己打包，然后在python环境下安装algorithm包
